name: Bug Report
description: Submit a bug report
title: "[Bug]: "
labels: [ "bug" ]
projects: "eeberhard/2"
assignees:
  - eeberhard
body:
  - type: markdown
    attributes:
      value: |
        To submit a bug report,
        1. Check if the bug has already been reported (search existing issues using the filter `[Bug] in:title`)
        2. Update the issue title above with a description of the bug (e.g `[Bug]: Component XYZ crashes when...`)
        3. Fill out the form fields below
        4. Press Submit
  - type: textarea
    id: manifest
    attributes:
      label: Image manifest
      description: Copy the full manifest file with the base version and any extras used to package your AICA runtime image
      render: Shell
      placeholder: |
        #syntax=ghcr.io/aica-technology/app-builder:v1

        [packages]
        "@aica/base" = "v1.2.3"
    validations:
      required: true
  - type: textarea
    id: brief-description
    attributes:
      label: Brief description
      description: Give a brief description of the bug
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the bug
    validations:
      required: true
  - type: textarea
    id: log-output
    attributes:
      label: Relevant log output
      description: Copy and paste any relevant log output resulting from the bug
      render: Shell
  - type: textarea
    id: attachments
    attributes:
      label: Supporting information
      description: Include any additional supporting information or attachments
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report! A member of the AICA team will look into it as soon as possible.
