name: Feature Request
description: Request a new feature
title: "[Request]: "
labels: ["enhancement"]
assignees:
  - eeberhard
body:
  - type: markdown
    attributes:
      value: |
        To submit a feature or change request,
        1. Check if a similar request has already been submitted (search existing issues using the filter `[Request] in:title`)
        2. Update the issue title above with a description of the request (e.g `[Request]: There should be...`)
        3. Fill out the form fields below
        4. Press Submit
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please give a description of the requested feature or change
    validations:
      required: true
  - type: textarea
    id: justification
    attributes:
      label: Who would benefit?
      description: Please justify the request by describing who would benefit from this feature or change
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Supporting information
      description: Include any additional supporting information or attachments
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a feature request! A member of the AICA team will look into it as soon as possible.