name: Question
description: Ask a question to get help or support
title: "[Question]: "
labels: ["documentation", "question"]
assignees:
  - eeberhard
body:
  - type: markdown
    attributes:
      value: |
        To ask a question,
        1. Check if your question has already been asked (search existing issues using the filter `[Question] in:title`)
        2. Update the issue title above with your question (e.g `[Question]: How do I...?`)
        3. Fill out the form fields below
        4. Press Submit
  - type: dropdown
    id: user
    attributes:
      label: Experience level
      description: Please indicate your experience level with AICA software
      options:
        - New user
        - Intermediate user
        - Expert user
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What is your question?
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Supporting information
      description: Include any additional supporting information or attachments
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a question! A member of the AICA team will get back to you as soon as possible.